### Send POST request with json body
POST http://localhost:8080/api/emprunts
Content-Type: application/json

{
  "adherent": {
    "prenom": "Marie",
    "nom": "Golotte"
  },
  "document": {
    "nom": "A la recherche du temps perdu",
    "description": "L'oeuvre de Marcel Proust"
  }
}

### Send POST request with json body
POST http://localhost:8080/api/emprunts
Content-Type: application/json

{
  "adherent": {
    "prenom": "Jean",
    "nom": "Bonneau"
  },
  "document": {
    "nom": "La grande chasse au requin",
    "description": "L'oeuvre de Hunter S. Thompson"
  }
}

### GET request with a header
GET http://localhost:8080/api/emprunts
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/emprunts/2
Accept: application/json
