### Send POST request with json body
POST http://localhost:8080/api/emprunts
Content-Type: application/json

{
  "adherent": {
    "id": 2,
    "prenom": "Marie",
    "nom": "Golotte",
    "dateFinAdhesion": "2024-12-31"
  },
  "document": {
    "id": 1,
    "nom": "A la recherche du temps perdu",
    "description": "L'oeuvre de Marcel Proust"
  }
}

### Send POST request with json body
POST http://localhost:8080/api/emprunts
Content-Type: application/json

{
  "adherent": {
    "id": 1,
    "prenom": "Jean",
    "nom": "Bonneau",
    "dateFinAdhesion": "2024-12-31"
  },
  "document": {
    "id": 2,
    "nom": "La grande chasse au requin",
    "description": "L'oeuvre de Hunter S. Thompson"
  }
}

### Send POST request with json body
POST http://localhost:8080/api/emprunts
Content-Type: application/json

{
  "adherent": {
    "id": 1,
    "prenom": "Jean",
    "nom": "Bonneau",
    "dateFinAdhesion": "2024-12-31"
  },
  "document": {
    "id": 1,
    "nom": "A la recherche du temps perdu",
    "description": "L'oeuvre de Marcel Proust"
  }
}

### GET request with a header
GET http://localhost:8080/api/emprunts
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/emprunts/4
Accept: application/json
